version: '3.6'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    extra_hosts:
      - localhost:host-gateway
    ports:
      - 5432:5432

  ecommerce_graphql_api:
    container_name: ecommerce_graphql_api
    image: praveennagaraj/ecommerce_graphql_api
    restart: always
    depends_on:
      - db
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:3000
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY}
      - NODE_ENV=${NODE_ENV}
      - CORS_WHITELIST=${CORS_WHITELIST}

    volumes:
      - .:/app
      - /node_modules
      - /.env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
